version: '3'
services:
  # App is an nginx reverse proxy that also serves the static files
  nginx:
    build:
      # this sets where the Dockerfile is allowed to copy from. 
      # Without backing up to the infrastructure root, permission to 
      # copy source code from the git submodule repo is denied.
      context: ../../
      # The context has been set so we need to jump back into this Dockerfile's dir
      dockerfile: ./_configs/microservice-http/nginx/Dockerfile
    image: app:0.5.0
    # TODO: Test if the context command sets context for volumes
    volumes:
    - ../../react-app/dist/index.html:/usr/share/nginx/html/index.html
    - ../../react-app/dist/static:/usr/share/nginx/html/static
    ports:
    - "80:80"
    links:
    - api
  api:
    build:
      context: ../../
      dockerfile: ./_configs/microservice-http/api/Dockerfile
    image: api:0.5.0
    volumes:
    - ../../api/api.js:/var/www/api/api.js
    - ../../api/src:/var/www/api/src
    environment:
    - ARANGODB_HOST=arango
    - ARANGODB_PORT=8529
    - ARANGODB_USERNAME=root
    - ARANGODB_PASSWORD=wlarango
    - ARANGODB_DB=wl_db
    ports:
    - "3030:3030"
    links:
    - arango
  arango:
    image: arangodb/arangodb:3.2.2
    ports:
    - "8529:8529"
    environment:
    - ARANGO_ROOT_PASSWORD=t
    - ARANGO_NO_AUTH=1
    - ARANGODB_USERNAME=t
    - ARANGODB_PASSWORD=t
    - ARANGODB_DB=t
    volumes:
    # /var/lib/arangodb-apps stores extensions
    - arango-collection-volume:/var/lib/arangodb
    - arango-log-volume:/var/log/arangodb
volumes:
  arango-collection-volume:
  arango-log-volume: